# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: pretty-format-json
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: fix-encoding-pragma
    -   id: requirements-txt-fixer

-   repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        language: python
        stages: [commit, push, manual]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        language: python
        stages: [commit, push, manual]
